export const PENDING = "PENDING";
export const ERROR = "ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"; 
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";


